---
- name: Install prerequisites
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    update_cache: yes

- name: Ensure apt keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    recurse: yes

- name: Download Docker-CE GPG keys
  ansible.builtin.shell:
    creates: /etc/apt/keyrings/docker.gpg
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg

- name: Set up Docker-CE repository
  ansible.builtin.shell:
    creates: /etc/apt/sources.list.d/docker.list
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes

- name: Install docker python module
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: Login to Github Container Registry
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ ghcr_user }}"
    password: "{{ ghcr_token }}"